version: "3.2"

services:
  # # provisioner
  # provision:
  #   image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:$TAG
  #   entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
  #   volumes: 
  #     - ./:/src/ # required
  #   environment:
  #     - __tc_fixes=$FIXES     # [] or ALL from the env

  # target container
  tc:
    image: daerepository03.eur.ad.sag:4443/ccdevops/terracotta-server:$TAG # target image
    build:
      context: .
      dockerfile: Dockerfile            # instructions to build image
      args:
        - TAG
        - __tc_fixes=$FIXES             # [] or ALL from the env
    ports:
      - 9010                            # container specific port
      - 9030                            # container specific port
      - 9040                            # container specific port
      - 8092                            # if CC-managed, SPM port
    hostname: tc01
    environment:
      - CC_AUTO_REGISTER=1              # No auto register as we don't have a server
      - OFFHEAP_MAX_SIZE=513m           # Customized offheap size
    # volumes:
    #   - ../../build/run/data/tc/store:/data/diskstore  # for data persistence
    #   - ../../build/run/data/tc/backup:/data/backup    # for data persistence
    #   - ./entrypoint.sh:/opt/softwareag/entrypoint.sh  # for dev only to avoid image rebuild
    #   - ./test.sh:/test.sh                             # for dev only to avoid image rebuild

networks:
  default:
    external:
      name: sagdevops-templates_default
