version: "3.2"

services:
  # # provisioner
  # provision:
  #   image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:$TAG
  #   entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
  #   volumes: 
  #     - ./:/src/ # required
  #       # TODO?: to have a volume, otherwise UM fails to start!
  #     - ../../build/run/data/umdev:/opt/softwareag/UniversalMessaging/server/default/data/
  #   environment:
  #     - __um_realm=default              # template test specific param
  #     - __um_fixes=$FIXES               # [] or ALL from the env
  
  # target container
  um:
    image: daerepository03.eur.ad.sag:4443/ccdevops/universal-messaging:$TAG # target image
    build:
      context: .
      dockerfile: Dockerfile            # instructions to build image
      args:
        - TAG
        - __um_fixes=$FIXES             # [] or ALL from the env
    ports:
      - "9000"                          # container specific ports
    hostname: um01
    environment:
      - CC_AUTO_REGISTER=1              # No auto register as we don't have a server
    # volumes:
    #   - ./entrypoint.sh:/opt/softwareag/entrypoint.sh # for dev only to avoid image rebuild
    #   - ./test.sh:/test.sh # for dev only to avoid image rebuild

networks:
  default:
    external:
      name: sagdevops-templates_default
