version: "3.2"

services:
  # provisioner
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:$TAG
    entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
    volumes: 
      - ./:/src/ # required
  
  # target container
  node:
    image: daerepository03.eur.ad.sag:4443/ccdevops/asset-builder:$TAG # target image
    build:
      context: .
      dockerfile: Dockerfile            # instructions to build image
    volumes:
      - ./test.sh:/test.sh # for dev only to avoid image rebuild
