version: "3.2"

services:
  # provisioner
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:$TAG
    entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
    volumes: 
      - ./:/src/ # required
  
  # target container
  node:
    image: daerepository03.eur.ad.sag:4443/ccdevops/microservices-runtime:$TAG # target image
    build:
      context: .
      dockerfile: Dockerfile            # instructions to build image
      args:
        - TAG
    ports:
      - "5555"                          # container specific ports
    environment:
      - CC_AUTO_REGISTER=0              # No auto register as we don't have a server
    volumes:
      - ./entrypoint.sh:/opt/softwareag/entrypoint.sh # for dev only to avoid image rebuild
      - ./test.sh:/test.sh # for dev only to avoid image rebuild
